"""Extract the 3.3.677 and 3.3.678 credits payloads. Requires pefile.

NOT PART OF THE ORIGINAL. Project tooling.
"""

import hashlib
from pathlib import Path

import pefile


ROOT = Path(__file__).resolve().parents[2]


def unpack(data):
    output = bytearray()
    zeros = 0
    for value in data:
        if zeros == 3:
            output.extend(bytes(value))
            zeros = 0
        else:
            output.append(value)
            zeros = zeros + 1 if value == 0 else 0
    return bytes(output)


def main():
    payloads = []
    for name, rva in [('rtl', 0x5F924), ('dbg', 0x1480E8), ('dbgv', 0x14B0E8)]:
        image = pefile.PE(str(ROOT / 'ref' / ('a3dapi_33_' + name + '.dll')))
        payloads.append(image.get_data(rva, 0x36CE))
    assert payloads[0] == payloads[1] == payloads[2]
    packed = payloads[0]
    program = unpack(packed)
    assert len(program) == 24576
    assert hashlib.sha256(program).hexdigest() == \
        'f64be515c5aa600cba702094fad1aefd75133eb5f50286baa773f19c112493fb'
    heading = ('/* Generated by tools/analysis/extract_easter_egg.py.\n'
               ' * (RE) rtl:0x1005f924; dbg:0x101480e8; dbgv:0x1014b0e8.\n'
               ' *\n'
               ' * Packed credits executable shared by the three 3.3.677 builds.\n'
               ' * Included as byte-array contents by rmbuffer.cpp, which expands\n'
               ' * zero runs and writes the program to a temporary file when the\n'
               ' * credits property is invoked.\n'
               ' *\n'
               ' * Regenerate from the reference DLLs with the named script; the\n'
               ' * byte values are extracted data, not hand-maintained source. */\n')
    rows = ['\t' + ', '.join('0x%02X' % c for c in packed[i:i + 16]) + ','
            for i in range(0, len(packed), 16)]
    (ROOT / 'src/a3dapi/easteregg.inc').write_text(heading + '\n'.join(rows) + '\n')

    image = pefile.PE(str(ROOT / 'ref/a3dapi_33_678.dll'))
    packed_new = image.get_data(0x5F9E4, 0x4293)
    program_new = unpack(packed_new)
    assert len(program_new) == 28672
    assert hashlib.sha256(program_new).hexdigest() == \
        'c1cb9b66ea6c9e485b11f4f1630577c2cb872d51d5e1ce8d2b7ac03d71636079'
    heading_new = ('/* Generated by tools/analysis/extract_easter_egg.py.\n'
                   ' * (RE) 678:0x1005f9e4.\n'
                   ' *\n'
                   ' * Packed credits executable from 3.3.678, selected by the\n'
                   ' * UseNewCredits runtime setting under A3D_FIXES. rmbuffer.cpp\n'
                   ' * includes both payloads in additions-enabled builds and handles\n'
                   ' * unpacking and launching the credits program.\n'
                   ' *\n'
                   ' * Regenerate from the reference DLL with the named script;\n'
                   ' * this is cross-version data, not the default 677 payload. */\n')
    rows_new = ['\t' + ', '.join('0x%02X' % c for c in packed_new[i:i + 16]) + ','
                for i in range(0, len(packed_new), 16)]
    (ROOT / 'src/a3dapi/easteregg_new.inc').write_text(
        heading_new + '\n'.join(rows_new) + '\n')
    print('Extracted 678: %d packed bytes, %d executable bytes.' %
          (len(packed_new), len(program_new)))

    print('Extracted %d packed bytes, %d executable bytes; all three 677 builds match.' % (len(packed), len(program)))


if __name__ == '__main__':
    main()
